<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RoslynCommonAnalyzersVersion>5.1.2</RoslynCommonAnalyzersVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="StyleSharp.Analyzers" Version="$(RoslynCommonAnalyzersVersion)" />
    <PackageVersion Include="PerformanceSharp.Analyzers" Version="$(RoslynCommonAnalyzersVersion)" />
    <PackageVersion Include="SecuritySharp.Analyzers" Version="$(RoslynCommonAnalyzersVersion)" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
    <PackageVersion Include="System.Management" Version="10.0.12" />
  </ItemGroup>
</Project>
