name: Common publish to GitHub Packages workflow

permissions:
  packages: write

on:
  workflow_call:
    inputs:
      artifactName:
        type: string
        default: 'nuget-packages'
        description: 'Name of the artifact containing .nupkg files to publish'

jobs:
  publish-github-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ inputs.artifactName }}

      - name: Setup .NET Environment
        uses: glennawatson/actions-common/.github/actions/dotnet-environment@main
        with:
          stamp-version: 'false'

      - name: Push to GitHub Packages
        uses: glennawatson/actions-common/.github/actions/github-packages-push@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
